import requests
import sys

# Récupérer le premier argument passé en ligne de commande
username = sys.argv[1]

urls = [
    "https://www.9gag.com/u/" + username,
    "https://independent.academia.edu/" + username,
    "https://audiojungle.net/user/" + username,
    "https://bitbucket.org/" + username,
    "https://" + username + ".blogspot.com",
    "https://www.chess.com/member/" + username,
    "https://www.clubhouse.com/@" + username,
    "https://www.codecademy.com/profiles/" + username,
    "https://www.codechef.com/users/" + username,
    "https://codeforces.com/profile/" + username,
    "https://coil.com/u/" + username,
    "https://disqus.com/" + username,
    "https://hub.docker.com/u/" + username,
    "https://dribbble.com/" + username,
    "https://www.eyeem.com/u/" + username,
    "https://www.fiverr.com/" + username,
    "https://fortnitetracker.com/profile/all/" + username,
    "https://www.freelancer.com/u/" + username,
    "https://www.g2g.com/" + username,
    "https://auth.geeksforgeeks.org/user/" + username,
    "https://www.github.com/" + username,
    "https://gitee.com/" + username,
    "https://www.gumroad.com/" + username,
    "https://news.ycombinator.com/user?id=" + username,
    "https://hackerrank.com/" + username,
    "https://hashnode.com/@" + username,
    "https://www.ifttt.com/p/" + username,
    "https://imgur.com/user/" + username,
    "https://www.instagram.com/" + username,
    "https://www.kaggle.com/" + username,
    "https://leetcode.com/" + username,
    "https://forums.mmorpg.com/profile/" + username,
    "https://www.mixcloud.com/" + username,
    "https://hellocode.newgrounds.com",
    "https://quizlet.com/" + username,
    "https://www.reddit.com/user/" + username,
    "https://replit.com/@" + username,
    "https://www.roblox.com/user.aspx?username=" + username,
    "https://scratch.mit.edu/users/" + username,
    "https://www.scribd.com/" + username,
    "https://www.smule.com/" + username,
    "https://www.snapchat.com/add/" + username,
    "https://soundcloud.com/" + username,
    "https://ch.tetr.io/u/" + username,
    "https://t.me/" + username,
    "https://themeforest.net/user/" + username,
    "https://tiktok.com/@" + username,
    "https://www.tradingview.com/u/" + username + "/",
    "https://tryhackme.com/p/" + username,
    "https://www.twitch.tv/" + username,
    "https://twitter.com/" + username,
    "https://vk.com/" + username,
    'https://discussions.apple.com/profile/' + username,
    'https://bodyspace.bodybuilding.com/' + username,
    'https://www.chess.com/member/' + username,
    'https://coil.com/u/' + username,
    'https://' + username + '.deviantart.com',
    'https://www.duolingo.com/profile/' + username,
    'https://www.etsy.com/shop/' + username,
    'https://www.eyeem.com/u/' + username,
    'https://www.fiverr.com/' + username,
    'https://fortnitetracker.com/profile/all/' + username,
    'https://www.freelancer.com/u/' + username,
    'https://www.g2g.com/' + username,
    'https://houzz.com/user/' + username,
    'https://www.instagram.com/' + username,
    'https://www.instructables.com/member/' + username,
    'https://kik.me/' + username,
    'https://quizlet.com/' + username,
    'https://www.reddit.com/user/' + username,
    'https://www.roblox.com/user.aspx?username=' + username,
    'https://www.scribd.com/' + username,
    'https://www.smule.com/' + username,
    'https://www.snapchat.com/add/' + username,
    'https://open.spotify.com/user/' + username,
    'https://tellonym.me/' + username,
    'https://tiktok.com/@' + username,
    'https://trello.com/' + username,
    'https://twitter.com/' + username,
    'https://vsco.co/' + username,
    'https://www.youtube.com/user/' + username,
    "https://www.codewars.com/users/" + username,
    "https://coil.com/u/" + username,
    "https://hub.docker.com/u/" + username + "/",
    "https://flipboard.com/@" + username,
    "https://www.freelancer.com/u/" + username,
    "https://www.g2g.com/" + username,
    "https://www.github.com/" + username,
    "https://www.gumroad.com/" + username,
    "https://leetcode.com/" + username,
    "https://linktr.ee/" + username,
    "https://www.reddit.com/user/" + username,
    "https://replit.com/@" + username,
    "https://www.roblox.com/user.aspx?username=" + username,
    "https://sketchfab.com/" + username,
    "https://tryhackme.com/p/" + username,
    "https://www.twitch.tv/" + username,
    "https://twitter.com/" + username,
    "https://www.wattpad.com/user/" + username,
    "https://en.wikipedia.org/wiki/Special:CentralAuth/" + username + "?uselang=qqx",
    "https://www.npmjs.com/~" + username
]
sorted(set(urls))

for url in urls:
    response = requests.get(url)
    if response.status_code == 200:
        if username in response.text:
            print(url)
